Parser 2.0
Get-Us-A-Mentor-Or-Something/C-ped pull request #20
Opened 2020-04-23 13:48 UTC by werdvolf

2020-04-24 09:50 UTC, LudwigVonChesterfield commented
А он чем-то лучше парсера который был до этого?

И да, пожалуйста, исправь ошибки на которые рычит линтер.

2020-04-24 09:51 UTC, LudwigVonChesterfield commented on Flask/code/parser_v1_0.py
> +def search(tags, min_=20, from_date=1457136000, to_date=1457222400):
Пожалуйста сделай эти цифры менее волшебными, мне лично не очень понятно к чему они тут.

2020-04-24 09:52 UTC, LudwigVonChesterfield commented
А зачем файлам писать в название "версию"? Мы всё же гитом пользуемся для вершон менеджмента...

2020-04-24 12:18 UTC, LudwigVonChesterfield requested changes

2020-04-24 12:18 UTC, LudwigVonChesterfield commented on Flask/code/parser_v2_0.py
> +    q = '%20'.join(q.split())
Что вот это %20 значит? Пожалуйста вынеси в отдельную переменную, чтобы оно не казалось таким волшебным.

2020-04-24 12:18 UTC, LudwigVonChesterfield commented on Flask/code/parser_v2_0.py
> +    url = 'https://stackoverflow.com/search?tab=Relevance&pagesize=50&q=' + q
Эта ссылка тоже выглядит довольно волшебной, почему нельзя задавать pagesize переменной? Почему нельзя сортировку использовать кроме "Relevance"? Это всё можно было бы вынести в конфиг.

2020-04-24 12:18 UTC, LudwigVonChesterfield commented on Flask/code/parser_v2_0.py
> +    all_code = collections.defaultdict(list)
Ты это используешь в двух местах, может стоит это вынести в функцию?

2020-04-24 13:58 UTC, werdvolf commented on Flask/code/parser_v2_0.py
> +    q = '%20'.join(q.split())
%20 - це так формується запит на стаку для 50 відповідей.
Для прикладу звичайний  запрос, там де 15 відповідей буде виглядати так - https://stackoverflow.com/search?q=python+sort
Запрос з 50 відповідями - https://stackoverflow.com/search?tab=Relevance&pagesize=50&q=python%20sort

2020-04-24 13:59 UTC, werdvolf commented on Flask/code/parser_v2_0.py
> +    url = 'https://stackoverflow.com/search?tab=Relevance&pagesize=50&q=' + q
Я це все внесу пізніше.

2020-04-24 14:19 UTC, LudwigVonChesterfield commented on Flask/code/parser_v2_0.py
> +    url = 'https://stackoverflow.com/search?tab=Relevance&pagesize=50&q=' + q
Ну... Так вноси.

2020-04-24 14:24 UTC, LudwigVonChesterfield commented on Flask/code/parser_v2_0.py
> +    q = '%20'.join(q.split())
%20 - это "символ" для разделения между тэгами(как я понял), я бы предложил сделать переменную аки "QUERY_SEPERATOR", и тогда эту строку можно было бы преобразить в
`query = QUERY_SEPERATOR.join(q.split())`

2020-04-26 18:53 UTC, LudwigVonChesterfield commented on Flask/code/parser_v2_0.py
> +    q = '%20'.join(q.split())
Я ещё чуть больше осведомился насчёт этого пункта. А нельзя было бы более красиво как-то переводить строку в совместимую для браузера? Может есть какая-то библиотека делающая это?

2020-05-27 21:12 UTC, LudwigVonChesterfield commented
#21

2020-05-27 21:12 UTC, closed without merging